// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_reasoning_content(
    object_19: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::ReasoningContent,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    match input {
        crate::types::ReasoningContent::ReasoningText(inner) => {
            #[allow(unused_mut)]
            let mut object_1 = object_19.key("reasoningText").start_object();
            crate::protocol_serde::shape_reasoning_text::ser_reasoning_text(&mut object_1, inner)?;
            object_1.finish();
        },
        crate::types::ReasoningContent::RedactedContent(inner) => {
            object_19
                .key("redactedContent")
                .string_unchecked(&::aws_smithy_types::base64::encode(inner));
        },
        crate::types::ReasoningContent::Unknown => {
            return Err(::aws_smithy_types::error::operation::SerializationError::unknown_variant("ReasoningContent"));
        },
    }
    Ok(())
}
