// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct ReasoningText {
    #[allow(missing_docs)] // documentation missing in model
    pub text: ::std::string::String,
    /// A token that verifies that the reasoning text was generated by the model
    pub signature: ::std::option::Option<::std::string::String>,
}
impl ReasoningText {
    #[allow(missing_docs)] // documentation missing in model
    pub fn text(&self) -> &str {
        use std::ops::Deref;
        self.text.deref()
    }

    /// A token that verifies that the reasoning text was generated by the model
    pub fn signature(&self) -> ::std::option::Option<&str> {
        self.signature.as_deref()
    }
}
impl ::std::fmt::Debug for ReasoningText {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ReasoningText");
        formatter.field("text", &"*** Sensitive Data Redacted ***");
        formatter.field("signature", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
impl ReasoningText {
    /// Creates a new builder-style object to manufacture
    /// [`ReasoningText`](crate::types::ReasoningText).
    pub fn builder() -> crate::types::builders::ReasoningTextBuilder {
        crate::types::builders::ReasoningTextBuilder::default()
    }
}

/// A builder for [`ReasoningText`](crate::types::ReasoningText).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
#[non_exhaustive]
pub struct ReasoningTextBuilder {
    pub(crate) text: ::std::option::Option<::std::string::String>,
    pub(crate) signature: ::std::option::Option<::std::string::String>,
}
impl ReasoningTextBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn text(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.text = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_text(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.text = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_text(&self) -> &::std::option::Option<::std::string::String> {
        &self.text
    }

    /// A token that verifies that the reasoning text was generated by the model
    pub fn signature(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.signature = ::std::option::Option::Some(input.into());
        self
    }

    /// A token that verifies that the reasoning text was generated by the model
    pub fn set_signature(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.signature = input;
        self
    }

    /// A token that verifies that the reasoning text was generated by the model
    pub fn get_signature(&self) -> &::std::option::Option<::std::string::String> {
        &self.signature
    }

    /// Consumes the builder and constructs a [`ReasoningText`](crate::types::ReasoningText).
    /// This method will fail if any of the following fields are not set:
    /// - [`text`](crate::types::builders::ReasoningTextBuilder::text)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::types::ReasoningText, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ReasoningText {
            text: self.text.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "text",
                    "text was not specified but it is required when building ReasoningText",
                )
            })?,
            signature: self.signature,
        })
    }
}
impl ::std::fmt::Debug for ReasoningTextBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("ReasoningTextBuilder");
        formatter.field("text", &"*** Sensitive Data Redacted ***");
        formatter.field("signature", &"*** Sensitive Data Redacted ***");
        formatter.finish()
    }
}
