// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_reasoning_text(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::ReasoningText,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    {
        object.key("text").string(input.text.as_str());
    }
    if let Some(var_1) = &input.signature {
        object.key("signature").string(var_1.as_str());
    }
    Ok(())
}
